import '../lib/investment_portfolio_model.dart';

// Compile with dart2js and execute with a Web Crypto implementation, so this
// regression exercises JavaScript integer semantics rather than only the VM.
void main() {
  final ids = List.generate(1000, (_) => newInvestmentId());
  if (ids.toSet().length != ids.length ||
      ids.any((id) => !RegExp(r'^\d+-[0-9a-f]{32}$').hasMatch(id))) {
    throw StateError('Invalid or repeated investment identifiers.');
  }
  print('PASS: 1000 unique investment IDs generated by compiled JavaScript.');
}
